[platformio]
default_envs = four-button
src_dir = variants

[env]
platform = espressif32@6.6.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -D CORE_DEBUG_LEVEL=0

[env:two-button]
build_src_filter = +<two-button/firmware/main.cpp>

[env:four-button]
build_src_filter = +<four-button/firmware/main.cpp>
