[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32@6.6.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -D CORE_DEBUG_LEVEL=0

